; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:micro]
platform = atmelavr
board = micro
#board = sparkfun_promicro16
#board = leonardo #maybe better HID support
framework = arduino
#upload_protocol = avr109
#monitor_speed = 115200
board_upload.use_1200bps_touch = no
#lib_deps = 
#	nicohood/HID-Project@^2.8.4
#build_flags = -DUSB_HID -DUSB_MANUFACTURER=\"Custom\" -DUSB_PRODUCT=\"LodgeNet\"
#build_flags = -DUSB_MANUFACTURER=\"YourName\" -DUSB_PRODUCT=\"LodgeNetController\" -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x8036 -DUSB_HID
#	-DUSB_CORE_HID
#    -DCDC_DISABLED

#build_flags = 
#    -I$PROJECT_SRC_DIR/arduino

#build_src_filter = +<src/main.cpp> +<src/arduino/*>
#upload_port = COM

#upload_protocol = buspirate
#upload_port = COM5
#upload_speed = 115200
#upload_speed = 57600
#upload_speed = 19200

#board_bootloader.file = F:\Downloads\Caterina-promicro16.hex

# fix (bad)
# "C:\Users\Nielk1\.platformio\packages\tool-avrdude\avrdude.exe" -v -C "C:\Users\Nielk1\.platformio\packages\tool-avrdude\avrdude.conf" -c buspirate -P COM5 -b 115200 -p atmega32u4 -e -U flash:w:Caterina-promicro16.hex:i -U lfuse:w:0xFF:m -U hfuse:w:0xD8:m -U efuse:w:0xCB:m

# fix (good)
# "C:\Users\Nielk1\.platformio\packages\tool-avrdude\avrdude.exe" -v -C "C:\Users\Nielk1\.platformio\packages\tool-avrdude\avrdude.conf" -c buspirate -P COM5 -b 115200 -p atmega32u4 -e -U flash:w:Caterina-Micro.hex:i -U lfuse:w:0xFF:m -U hfuse:w:0xD8:m -U efuse:w:0xCB:m
