; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:micro]
platform = atmelavr
board = micro
#board = leonardo #maybe better HID support
framework = arduino
monitor_speed = 115200
board_upload.use_1200bps_touch = no
#lib_deps = 
#	nicohood/HID-Project@^2.8.4
#build_flags = -DUSB_HID -DUSB_MANUFACTURER=\"Custom\" -DUSB_PRODUCT=\"LodgeNet\"